#!/usr/bin/env python3
from html import escape
from pathlib import Path


# Edit these strings, then run:
#   python3 scripts/generate_typing_svg.py
QUOTE_1_LINES = (
    "If I simulate further,",
    "it is by standing on the shoulders of open-source codes.",
)
QUOTE_2 = "What I cannot simulate, I do not understand."

CANVAS_WIDTH = 780
CANVAS_HEIGHT = 90
CHAR_WIDTH = 12
FONT_SIZE = 20
TEXT_COLOR = "#d97706"
DURATION = "13s"

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets" / "typing.svg"


def measure(text):
    return len(text) * CHAR_WIDTH


def centered_x(text):
    width = measure(text)
    x = (CANVAS_WIDTH - width) // 2
    if x < 0:
        raise ValueError(f"Text is too wide for {CANVAS_WIDTH}px canvas: {text}")
    return x


def text_node(text, x, y, clip_id):
    return f'''  <g clip-path="url(#{clip_id})">
    <text x="{x}" y="{y}">{escape(text)}</text>
  </g>'''


def main():
    quote1_line1, quote1_line2 = QUOTE_1_LINES
    quote2 = QUOTE_2

    q1_l1_x = centered_x(quote1_line1)
    q1_l2_x = centered_x(quote1_line2)
    q2_x = centered_x(quote2)

    q1_l1_w = measure(quote1_line1)
    q1_l2_w = measure(quote1_line2)
    q2_w = measure(quote2)

    aria_label = escape(f"{quote1_line1} {quote1_line2} {quote2}", quote=True)
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS_WIDTH}" height="{CANVAS_HEIGHT}" viewBox="0 0 {CANVAS_WIDTH} {CANVAS_HEIGHT}" role="img" aria-label="{aria_label}">
  <title>Typing SVG</title>
  <!-- Generated by scripts/generate_typing_svg.py. -->
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Space+Mono&amp;display=swap");

    text {{
      fill: {TEXT_COLOR};
      font-family: "Space Mono", "Courier New", monospace;
      font-size: {FONT_SIZE}px;
      font-style: normal;
      font-weight: 400;
    }}

    .cursor {{
      animation: blink 0.7s step-end infinite;
      fill: {TEXT_COLOR};
    }}

    @keyframes blink {{
      50% {{
        opacity: 0;
      }}
    }}
  </style>

  <defs>
    <clipPath id="quote1-line1">
      <rect x="{q1_l1_x}" y="12" width="0" height="24">
        <animate attributeName="width" values="0;{q1_l1_w};{q1_l1_w};{q1_l1_w};0;0" keyTimes="0;0.10;0.45;0.53;0.56;1" dur="{DURATION}" repeatCount="indefinite" />
      </rect>
    </clipPath>
    <clipPath id="quote1-line2">
      <rect x="{q1_l2_x}" y="42" width="0" height="24">
        <animate attributeName="width" values="0;0;{q1_l2_w};{q1_l2_w};0;0" keyTimes="0;0.10;0.37;0.45;0.53;1" dur="{DURATION}" repeatCount="indefinite" />
      </rect>
    </clipPath>
    <clipPath id="quote2">
      <rect x="{q2_x}" y="29" width="0" height="24">
        <animate attributeName="width" values="0;0;{q2_w};{q2_w};0;0" keyTimes="0;0.58;0.82;0.90;0.98;1" dur="{DURATION}" repeatCount="indefinite" />
      </rect>
    </clipPath>
  </defs>

{text_node(quote1_line1, q1_l1_x, 31, "quote1-line1")}
{text_node(quote1_line2, q1_l2_x, 61, "quote1-line2")}
{text_node(quote2, q2_x, 48, "quote2")}
  <rect class="cursor" x="{q1_l1_x}" y="13" width="3" height="23" visibility="hidden">
    <animate attributeName="visibility" values="visible;visible;hidden;hidden" keyTimes="0;0.56;0.561;1" dur="{DURATION}" repeatCount="indefinite" />
    <animate attributeName="x" values="{q1_l1_x};{q1_l1_x + q1_l1_w};{q1_l2_x};{q1_l2_x + q1_l2_w};{q1_l2_x + q1_l2_w};{q1_l2_x};{q1_l1_x + q1_l1_w};{q1_l1_x};{q1_l1_x}" keyTimes="0;0.10;0.101;0.37;0.45;0.53;0.531;0.56;1" dur="{DURATION}" repeatCount="indefinite" />
    <animate attributeName="y" values="13;13;43;43;43;43;13;13;13" keyTimes="0;0.10;0.101;0.37;0.45;0.53;0.531;0.56;1" dur="{DURATION}" repeatCount="indefinite" />
  </rect>
  <rect class="cursor" x="{q2_x}" y="30" width="3" height="23" visibility="hidden">
    <animate attributeName="visibility" values="hidden;hidden;visible;visible;hidden;hidden" keyTimes="0;0.58;0.581;0.98;0.981;1" dur="{DURATION}" repeatCount="indefinite" />
    <animate attributeName="x" values="{q2_x};{q2_x};{q2_x + q2_w};{q2_x + q2_w};{q2_x};{q2_x}" keyTimes="0;0.58;0.82;0.90;0.98;1" dur="{DURATION}" repeatCount="indefinite" />
  </rect>
</svg>
'''
    OUTPUT.write_text(svg, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
